deploy:

    needs: test-build

    runs-on: ubuntu-latest



    strategy:

      matrix:

        node-version: [16.x]



    steps:

      - name: Build app on VM

        uses: appleboy/ssh-action@master

        with:

          host: ${{secrets.HOST}}

          username: ${{secrets.USERNAME}}

          password: ${{secrets.PASSWORD}}

          port: ${{secrets.PORT}}

          script: |

            eval "$(ssh-agent -s)"

            ssh-add ~/.ssh/senpro-ssh

            cd ~/senpro/463613/modul01/senpro-github-action

            git restore

            git pull origin main

            npm install

            npm run build